# -*- coding: utf-8 -*-
"""Experian Step-Up CareerChallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRp5Iohz6F_FpMurBcp-fxcWQslXYgeJ
"""

#Money Mule Account Analysis
import pandas as pd

# Load the data
# Updated file paths to reflect location relative to the script
accounts = pd.read_csv("Step Up - Experian Account Data.csv")
holders = pd.read_csv("Step Up - Experian Acount Holder Data.csv")
mule_flags = pd.read_csv("Mule Flag.csv")

# Quick look at data
print(accounts.head())
print(holders.head())
print(mule_flags.head())

# Quick look at data
print(accounts.head())
print(holders.head())
print(mule_flags.head())

from datetime import datetime
import matplotlib.pyplot as plt
# Check for missing data and duplicates
print(accounts.isnull().sum())
print(holders.isnull().sum())
print(mule_flags.isnull().sum())

# Drop duplicates
holder_df = holders.drop_duplicates()

# Step 3: Clean Data
accounts.fillna(-1, inplace=True)
holder_df.fillna({
    'DateOfBirth': 'Missing',
    'Gender': 'Missing',
    'Income': -1,
    'CreditScore': -1,
    'LoanAmount': -1,
    'EmploymentStatus': 'Missing',
    'MaritalStatus': 'Missing',
    'OccupancyStatus': 'Missing',
    'NumDependents': -1,
    'SocialMediaUsageHours': -1,
    'ShoppingFrequencyPerMonth': -1,
    'HealthInsuranceStatus': 'Missing'
}, inplace=True)
mule_flags.fillna(0, inplace=True)

# Step 4: Merge Everything
merged = accounts.merge(holder_df, on='Identifier', how='left')
merged = merged.merge(mule_flags, on='Identifier', how='left')

# Step 5: Feature Engineering
# Age calculation
today = datetime.today()
merged['DateOfBirth'] = pd.to_datetime(merged['DateOfBirth'], format='%d/%m/%Y', errors='coerce')
merged['Age'] = merged['DateOfBirth'].apply(lambda dob: today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day)) if pd.notnull(dob) else -1)

# Age Groups
age_bins = [0, 17, 24, 35, 45, 60, 100]
age_labels = ['0-17', '18-24', '25-35', '36-45', '46-60', '60+']
merged['AgeGroup'] = pd.cut(merged['Age'], bins=age_bins, labels=age_labels, right=False)

# Step 6: Analysis
# Mule distribution by AgeGroup and Gender
age_dist = merged.groupby('AgeGroup')['MuleAccount'].sum()
gender_dist = merged.groupby('Gender')['MuleAccount'].sum()

print("Mules by Age Group:")
print(age_dist)

print("Mules by Gender:")
print(gender_dist)

# Step 7: Visualization
plt.figure(figsize=(10, 5))
age_dist.plot(kind='bar', color='skyblue')
plt.title('Mules by Age Group')
plt.ylabel('Number of Mule Accounts')
plt.show()

plt.figure(figsize=(6, 4))
gender_dist.plot(kind='bar', color='lightgreen')
plt.title('Mules by Gender')
plt.ylabel('Number of Mule Accounts')
plt.show()